---
- name: CentOS | Download SPM Client repo
  get_url:
    url: https://pub-repo.sematext.com/centos/sematext-centos-repo.noarch.rpm
    dest: /tmp/sematext.rpm

- name: CentOS | Install repo
  yum:
    name: /tmp/sematext.rpm
    state: present

- name: CentOS | Install SPM Monitor
  yum:
    name: spm-client
    state: latest
    update_cache: yes
