---
- name: CentOS | Install ca-ceritificates and java-latest-openjdk-headless
  yum:
    name:
      - ca-ceritificates
      - java-latest-openjdk-headless
    state: latest
    update_cache: yes

- name: CentOS | Download Sematext Agent repo
  get_url:
    url: https://pub-repo.sematext.com/centos/sematext.repo
    dest: /etc/yum.repos.d/sematext.repo

- name: CentOS | Install Sematext Agent
  yum:
    name: sematext-agent
    state: latest
    update_cache: yes
