---
- name: Ubuntu | Check installed packages
  package_facts:
    manager: "auto"

- name: Ubuntu | Install ca-certificates
  apt:
    pkg: ca-certificates
    state: latest
    update_cache: yes

- name: Ubuntu | Install default-jre
  apt:
    pkg: default-jre
    state: latest
    update_cache: yes
  when: "'default-jre' not in ansible_facts.packages"

- name: Ubuntu | Add Sematext Agent repo key
  apt_key:
    url: https://pub-repo.sematext.com/ubuntu/sematext.gpg.key
    state: present

- name: Ubuntu | Add Sematext Agent repo
  apt_repository:
    repo: "deb http://pub-repo.sematext.com/ubuntu sematext main"
    state: present

- name: Ubuntu | Install Sematext Agent
  apt:
    pkg: sematext-agent
    state: latest
    update-cache: yes
