---
- name: RedHat | Check installed packages
  package_facts:
    manager: "auto"

- name: RedHat | Install ca-ceritificates
  yum:
    name: ca-ceritificates
    state: latest
    update_cache: yes

- name: RedHat | Install java-openjdk-headless
  yum:
    name: java-openjdk-headless
    state: latest
    update_cache: yes
  when: "'java-openjdk-headless' not in ansible_facts.packages"

- name: RedHat | Download Sematext Agent repo
  get_url:
    url: https://pub-repo.sematext.com/redhat/sematext.repo
    dest: /etc/yum.repos.d/sematext.repo

- name: RedHat | Install Sematext Agent
  yum:
    name: sematext-agent
    state: latest
    update_cache: yes
