---
- name: Fedora | Install ca-ceritificates and java-latest-openjdk-headless
  dnf:
    name:
      - ca-ceritificates
      - java-latest-openjdk-headless
    state: latest
    update_cache: yes

- name: Fedora | Download Sematext Agent repo
  get_url:
    url: https://pub-repo.sematext.com/fedora/sematext.repo
    dest: /etc/dnf.repos.d/sematext.repo

- name: Fedora | Install Sematext Agent
  dnf:
    name: sematext-agent
    state: latest
    update_cache: yes
