---
- name: Debian | Check installed packages
  package_facts:
    manager: "auto"

- name: Debian | Install ca-ceritificates
  apt:
    pkg: ca-ceritificates
    state: latest
    update_cache: yes

- name: Debian | Install default-jre
  apt:
    pkg: default-jre
    state: latest
    update_cache: yes
  when: "'default-jre' not in ansible_facts.packages"

- name: Debian | Add Sematext Agent repo key
  apt_key:
    url: https://pub-repo.sematext.com/debian/sematext.gpg.key
    state: present

- name: Debian | Add Sematext Agent repo
  apt_repository:
    repo: "deb http://pub-repo.sematext.com/debian sematext main"
    state: present

- name: Debian | Install Sematext Agent
  apt:
    pkg: sematext-agent
    state: latest
    update-cache: yes