---
- name: Debian | Install default-jre and ca-ceritificates
  apt:
    pkg: 
    - default-jre
    - ca-ceritificates
    state: latest
    update-cache: yes

- name: Debian | Add Sematext Agent repo key
  apt_key:
    url: https://pub-repo.sematext.com/debian/sematext.gpg.key
    state: present

- name: Debian | Add Sematext Agent repo
  apt_repository:
    repo: "deb http://pub-repo.sematext.com/debian sematext main"
    state: present

- name: Debian | Install Sematext Agent
  apt:
    pkg: sematext-agent
    state: latest
    update-cache: yes